myname=str(input("Please write your name :"))
print("The name is "+myname)
lowercase=str.lower(myname)
print("The name in lower case is "+lowercase)
uppercase=str.upper(myname)
print("The name in upper case is "+uppercase)
title=str.title(myname)
print("The name in title case is "+title)
numberofcharacters=len(myname)
print("The number of characters in the name is "+str(numberofcharacters))
count=myname.find("i")
if count!=-1:
    print("The first occurrence of 'i' is at index "+str(count))
else:
    print("The character 'i' is not found in the name")